### ISSUE TITLE
Cannot open admin page

### ISSUE THREAD

**Issue by everwanna** [StaticJsCMS/static-cms-gatsby-netlify-template#24]
Hello,

I have deployed to netlify. The blog posts look good. But when I open the admin page and clicked on the "LOGIN WITH NETLIFY IDENTITY" button, no login form appeared. From the console log I can see:

```js
Uncaught ReferenceError: setImmediate is not defined
    at cms-identity.js:25:1
    at cms.js:1:1594
    at cms.js:1:1597
```

I am new to the static cms. Can anyone help? Thank you!

**Comment by KaneFreeman** [comment]
That error is unrelated. This appears to be a timing error (related to https://github.com/StaticJsCMS/static-cms/issues/541). I am hoping to have this addressed for the next major release coming in the next month. For now simply wait a couple of seconds after the page loads before clicking the button.

**Comment by everwanna** [comment]
Thank you for your reply. However, I still cannot open the admin page after a few seconds. It says: "[Unable to access identity settings. When using git-gateway backend make sure to enable Identity service and Git Gateway.](https://docs.netlify.com/visitor-access/git-gateway/#setup-and-settings)".

**Comment by KaneFreeman** [comment]
That error will occur when you don't have git gateway setup correctly. You will need to follow the instructions in the linked article.

**Comment by everwanna** [comment]
I deployed it again and it worked! Thank you for your help.
